/**
 * @file tpvalg.c
 * @author Дмитрий Крысин <krysin@tecon.ru>
 * @date 2020
 * @brief
 */

//------------------------------------------------------------------------------
// includes
//------------------------------------------------------------------------------
#include <stdio.h>
#include <stdint.h>
#include <string.h>

char copyright[] = "\n  ELIZA/DOCTOR"
"\n  CREATED BY JOSEPH WEIZENBAUM"
"\n  THIS VERSION BY JEFF SHRAGER"
"\n  EDITED AND MODIFIED FOR MITS 8K BASIC 4.0 BY STEVE NORTH"
"\n  CREATIVE COMPUTING PO BOX 789-M MORRISTOWN NJ 07960";

//KEYWORDS
char keywords[16][] = {
"CAN YOU","CAN I","YOU ARE","YOURE","I DONT","I FEEL",
"WHY DONT YOU","WHY CANT I","ARE YOU","I CANT","I AM"," IM ",
"YOU","I WANT","WHAT","HOW","WHO","WHERE","WHEN","WHY",
"NAME","CAUSE","SORRY","DREAM","HELLO","HI","MAYBE",
"NO","YOUR","ALWAYS","THINK","ALIKE","YES","FRIEND",
"COMPUTER","NOKEYFOUND",
};

//STRING DATA FOR CONJUGATIONS
char conjstrs[10][] = {
	" ARE "," AM ","WERE ","WAS "," YOU "," I ","YOUR ","MY ".,
	" IVE "," YOUVE "," IM "," YOURE ",
};

// REPLIES
char replies[100][] = {
	"DON'T YOU BELIEVE THAT I CAN.",
	"PERHAPS YOU WOULD LIKE TO BE ABLE TO.",
	"YOU WANT ME TO BE ABLE TO*",
	"PERHAPS YOU DON'T WANT TO*",
	"DO YOU WANT TO BE ABLE TO*",
	"WHAT MAKES YOU THINK I AM*",
	"DOES IT PLEASE YOU TO BELIEVE I AM*",
	"PERHAPS YOU WOULD LIKE TO BE*",
	"DO YOU SOMETIMES WISH YOU WERE*",
	"DON'T YOU REALLY*",
	"WHY DON'T YOU*",
	"DO YOU WISH TO BE ABLE TO*",
	"DOES THAT TROUBLE YOU?",
	"TELL ME MORE ABOUT SUCH FEELINGS*",
	"DO YOU OFTEN FEEL*",
	"DO YOU ENJOY FEELING*",
	"DO YOU REALLY BELIEVE I DON'T*",
	"PERHAPS IN G00D TIME I WILL*",
	"DO YOU WANT ME TO*",
	"DO YOU THINK YOU SHOULD BE ABLE TO*",
	"WHY CAN'T YOU*",
	"WHY ARE YOU INTERESTED IN WHETHER OR NOT I AM*",
	"WOULD YOU PREFER IF I WERE NOT*",
	"PERHAPS IN YOUR FANTASIES I AM*",
	"HOW DO YOU KNOW YOU CAN'T*",
	"HAVE YOU TRIED?",
	"PERHAPS YOU CAN NOW*",
	"DID YOU COME TO ME BECAUSE YOU ARE*",
	"HOW LONG HAVE YOU BEEN*",
	"DO YOU BELIEVE IT IS NORMAL TO BE*",
	"DO YOU ENJOY BEING*",
	"WE WERE DISCUSSING YOU-- NOT ME.",
	"OH, I*",
	"YOU'RE NOT REALLY TALKING ABOUT ME. ARE YOU?",
	"WHAT WOULD IT MEAN TO YOU IF YOU GOT*",
	"WHY DO YOU WANT*",
	"SUPPOSE YOU SOON GOT*",
	"WHAT IF YOU NEVER GOT*",
	"I SOMETIMES ALSO WANT*",
	"WHY DO YOU ASK?",
	"DOES THAT QUESTION INTEREST YOU?",
	"WHAT ANSWER WOULD PLEASE YOU THE MOST?",
	"WHAT DO YOU THINK?",
	"ARE SUCH QUESTIONS ON YOUR MIND OFTEN?",
	"WHAT IS IT THAT YOU REALLY WANT TO KNOW?",
	"HAVE YOU ASKED ANYONE ELSE?",
	"HAVE YOU ASKED SUCH QUESTIONS BEFORE?",
	"WHAT ELSE COMES TO MIND WHEN YOU ASK THAT?",
	"NAMES DON'T INTEREST ME.",
	"I DON'T CARE ABOUT NAMES-- PLEASE GO ON.",
	"IS THAT THE REAL REASON?",
	"DON'T ANY OTHER REASONS COME TO MIND?",
	"DOES THAT REASON EXPLAIN ANYTHING ELSE?",
	"WHAT OTHER REASONS MIGHT THERE BE?",
	"PLEASE DON'T APOLOGIZE.",
	"APOLOGIES ARE NOT NECESSARY.",
	"WHAT FEELINGS DO YOU HAVE WHEN YOU APOLOGIZE.",
	"DON'T BE SO DEFENSIVE!",
	"WHAT DOES THAT DREAM SUGGEST TO YOU?",
	"DO YOU DREAM OFTEN?",
	"WHAT PERSONS APPEAR IN YOUR DREAMS?",
	"ARE YOU DISTURBED BY YOUR DREAMS?",
	"HOW DO YOU DO .,. PLEASE STATE YOUR PROBLEM.",
	"YOU DON'T SEEM QUITE CERTAIN.",
	"WHY THE UNCERTAIN TONE?",
	"CAN'T YOU BE MORE POSITIVE?",
	"YOU AREN'T SURE?",
	"DON'T YOU KNOW?",
	"ARE YOU SAYING NO JUST TO BE NEGATIVE?",
	"YOU ARE BEING A BIT NEGATIVE.",
	"WHY NOT?",
	"ARE YOU SURE?",
	"WHY NO?",
	"WHY ARE YOU CONCERNED ABOUT MY*",
	"WHAT ABOUT YOUR OWN*",
	"CAN'T YOU THINK OF A SPECIFIC EXAMPLE?",
	"WHEN?",
	"WHAT ARE YOU THINKING OF?",
	"REALLY. ALWAYS?",
	"DO YOU REALLY THINK SO?",
	"BUT YOU ARE NOT SURE YOU.",
	"DO YOU DOUBT YOU.",
	"IN WHAT WAY?",
	"WHAT RESEMBLANCE DO YOU SEE?",
	"WHAT DOES THE SIMILARITY SUGGEST TO YOU?",
	"WHAT OTHER CONNECTIONS DO YOU SEE?",
	"COULD THERE REALLY BE SOME CONNECTION?"
	"HOW?",
	"YOU SEEM QUITE POSITIVE.",
	"ARE YOU SURE?",
	"I SEE.",
	"I UNDERSTAND.",
	"WHY DO YOU BRING UP THE TOPIC OF FRIENDS?",
	"DO YOUR FRIENDS WORRY YOU?",
	"DO YOUR FRIENDS PICK ON YOU?",
	"ARE YOU SURE YOU HAVE ANY FRIENDS?",
	"DO YOU IMPOSE ON YOUR FRIENDS?",
	"PERHAPS YOUR LOVE FOR FRIENDS WORRIES YOU.",
	"DO COMPUTERS WORRY YOU?",
	"ARE YOU TALKING ABOUT ME IN PARTICULAR?",
	"ARE YOU FRIGHTENED BY MACHINES?",
	"WHY DO YOU MENTION COMPUTERS?",
	"WHAT DO YOU THINK MACHINES HAVE TO DO WITH YOUR PROBLEM?",
	"DON'T YOU THINK COMPUTERS CAN HELP PEOPLE?",
	"WHAT IS IT ABOUT MACHINES THAT WORRIES YOU?",
	"SAY, DO YOU HAVE ANY PSYCHOLOGICAL PROBLEMS?",
	"WHAT DOES THAT SUGGEST TO YOU?",
	"I SEE.",
	"I'M NOT SURE I UNDERSTAND YOU FULLY.",
	"COME COME ELUCIDATE YOUR THOUGHTS.",
	"CAN YOU ELABORATE ON THAT?",
	"THAT IS QUITE INTERESTING.",
};

// DATA FOR FINDING RIGHT REPLIES
int replies_idx[] = {
	1,3,4,2,6,4,6,4,10,4,14,3,17,3,20,2,22,3,25,3
	28,4,28,4,32,3,35,5,40,9,40,9,40,9,40,9,40,9,40,9
	49,2,51,4,55,4,59,4,63,1,63,1,64,5,69,5,74,2,76,4
	80,3,83,7,90,3,93,6,99,7,106,6
};

int s(36),r(36), n(36);
int n1=36, n2=12, n3=112;
char str_in[100];

120 FOR X=1 TO N1+N2+N3:READ Z$:NEXT X:REM SAME AS RESTORE
130 FOR X=1 TO N1
140 READ S(X),L:R(X)=S(X):N(X)=S(X)+L-1
150 NEXT X
170
	while(1) {
		printf("\HI! I'M ELIZA. WHAT'S YOUR PROBLEM?\n");
		//-----USER INPUT SECTION-----
		printf(">");
		gets(str_in);
201 I$=" "+I$+"  "
	// GET RID OF APOSTROPHES
220 FOR L=1 TO LEN(I$)
230 IF MID$(I$,L,1)="'"THEN I$=LEFT$(I$,L-1)+RIGHT$(I$,LEN(I$)-L):GOTO 230
240 IF L+4<=LEN(I$)THEN IF MID$(I$,L,4)="SHUT" THEN PRINT"SHUT UP...":END
250 NEXT L
255 IF I$=P$ THEN PRINT "PLEASE DON'T REPEAT YOURSELF!":GOTO 170
	// -----FIND KEYWORD IN I$-----
290 RESTORE
295 S=0
300 FOR K=1 TO N1
310 READ K$
315 IF S>0 THEN 360
320 FOR L=1 TO LEN(I$)-LEN(K$)+1
340 IF MID$(I$,L,LEN(K$))=K$THEN S=K:T=L:F$=K$
350 NEXT L
360 NEXT K
365 IF S>0 THEN K=S:L=T:GOTO 390
370 K=36:GOTO 570 //REM WE DIDN'T FIND ANY KEYWORDS

	// TAKE RIGHT PART OF STRING AND CONJUGATE IT
	// USING THE LIST OF STRINGS TO BE SWAPPED

420 RESTORE:FOR X=1 TO N1:READ Z$:NEXT X:REM SKIP OVER KEYWORDS
430 C$=" "+RIGHT$(I$,LEN(I$)-LEN(F$)-L+1)
440 FOR X=1 TO N2/2
450 READ S$,R$
460 FOR L= 1 TO LEN(C$)
470 IF L+LEN(S$)>LEN(C$) THEN 510
480 IF MID$(C$,L,LEN(S$))<>S$ THEN 510
490 C$=LEFT$(C$,L-1)+R$+RIGHT$(C$,LEN(C$)-L-LEN(S$)+1)
495 L=L+LEN(R$)
500 GOTO 540
510 IF L+LEN(R$)>LEN(C$)THEN 540
520 IF MID$(C$,L,LEN(R$))<>R$ THEN 540
530 C$=LEFT$(C$,L-1)+S$+RIGHT$(C$,LEN(C$)-L-LEN(R$)+1)
535 L=L+LEN(S$)
540 NEXT L
550 NEXT X
555 IF MID$(C$,2,1)=" "THEN C$=RIGHT$(C$,LEN(C$)-1):REM ONLY 1 SPACE

	// NOW USING THE KEYWORD NUMBER (K) GET REPLY

590 RESTORE:FOR X= 1 TO N1+N2:READ Z$:NEXT X
600 FOR X=1 TO R(K):READ F$:NEXT X:REM READ RIGHT REPLY
610 R(K)=R(K)+1: IF R(K)>N(K) THEN R(K)=S(K)
620 IF RIGHT$(F$,1 )<>"*" THEN PRINT F$:P$=I$:GOTO 170
630 PRINT LEFT$(F$,LEN(F$)-1);C$
640 P$=I$:
	}

